name: Push directory to another repository
description: >-
  Useful to push files to another repository to be used, for example, via github
  pages
inputs:
  user-email:
    description: Email for the git commit
    required: true
  user-name:
    description: >-
      [Optional] Name for the git commit. Defaults to the destination
      username/organization name
    required: false
    default: ''
  destination-repository-username:
    description: '[Optional] Username/organization for the destination repository'
    required: false
    default: ''
  api-specs-branch:
    description: the branch of qingcloud-api-specs to sync
    required: false
    default: 'master'
  branch-sdk-main:
    description: the base branch of qingcloud-sdk
    required: false
    default: 'master'
  branch-sdk-sync:
    description: the branch of qingcloud-sdk which will push
    required: false
    default: 'api-specs-sync'
  api-specs-repository-name:
    description: the repository name of qingcloud-api-specs
    required: false
    default: 'qingcloud-api-specs'
  java-sdk-repository-name:
    description: the repository name of qingcloud-sdk-java
    required: false
    default: 'qingcloud-sdk-java'
  go-sdk-repository-name:
    description: the repository name of qingcloud-sdk-go
    required: false
    default: 'qingcloud-sdk-go'
  ruby-sdk-repository-name:
    description: the repository name of qingcloud-sdk-ruby
    required: false
    default: 'qingcloud-sdk-ruby'
  commit-message:
    description: >-
      [Optional] commit message for the output repository. ORIGIN_COMMIT is
      replaced by the URL@commit in the origin repo
    default: Update from ORIGIN_COMMIT
    required: false
        
runs:
  using: docker
  image: Dockerfile
  args:
    - '${{ inputs.user-email }}'
    - '${{ inputs.user-name }}'
    - '${{ inputs.destination-repository-username }}'
    - '${{ inputs.api-specs-branch }}'
    - '${{ inputs.branch-sdk-main }}'
    - '${{ inputs.branch-sdk-sync }}'
    - '${{ inputs.api-specs-repository-name }}'
    - '${{ inputs.java-sdk-repository-name }}'
    - '${{ inputs.go-sdk-repository-name }}'
    - '${{ inputs.ruby-sdk-repository-name }}'
    - '${{ inputs.commit-message }}'

branding:
  icon: git-commit
  color: green
